name: Github actions build - Meme Generator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./projects/meme-generator

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install system dependencies
      run: |
        # required for pdftotext
        sudo apt-get install poppler-utils
    - name: Lint with flake8
      run: |
        flake8  --show-source --statistics
    - name: Test with pytest and generate coverage report
      run: |
        pytest \
          --doctest-modules \
          --junitxml=junit/test-results.xml \
          --cov=src \
          --cov-report=xml \
          --cov-report=html
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: ./**/meme-generator/junit/test-results.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: meme-generator
        fail_ci_if_error: true

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/junit/test-results.xml
