name: Meme Generator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./projects/meme-generator

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install system dependencies
      run: |
        sudo apt-get install poppler-utils
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest and generate coverage report
      run: |
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: coverage.xml
        flags: meme-generator
        env_vars: OS,PYTHON
        fail_ci_if_error: true
